# This workflow builds a Docker image and pushes it to DigitalOcean's Container Registry
name: Create Docker Image and Push to ACR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: npl-service
  TAG: latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build container image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Get the repo
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      # Login to ACR
      - name: Log into registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      # Build and push to ACR with given image name and tag
      - name: Build & Push
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          
          
          
