name: Delete Artifacts

on:
    schedule:
      - cron: '0 0 * * *' # Runs every day at midnight
    workflow_dispatch:

jobs:
  delete_artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Delete old artifacts
      uses: actions/github-script@v5
      with:
        script: |
          const { repo: { owner, repo } } = context;
          const artifacts = await github.rest.actions.listArtifactsForRepo({
            owner,
            repo
          });
          console.log(`Found ${artifacts.data.total_count} artifacts.`);
          for (const artifact of artifacts.data.artifacts) {
            console.log(`Deleting artifact: ${artifact.name} (ID: ${artifact.id})`);
            await github.rest.actions.deleteArtifact({
              owner,
              repo,
              artifact_id: artifact.id
            });
          }
